let listaAutores = [
  {
    id: "1",
    nombreCompleto: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "1927",
    fechaDefuncion: "2004",
    genero: "masculino",
    librosPublicados: [
      "Cien años de Soledad (1967)",
      "El amor en el tiempo del cólera (1985)",
      "El coronel no tiene quien le escriba (1961)",
      "Memorias de mis putas tristes (2004)",
    ],
    nobel: true,
    anoNobel: "1982",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "1904",
    fechaDefuncion: "1973",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },

  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
  {
    id: "1",
    nombreCompleto: "",
    img: "/ProjectGM_IMG/autores/",
    paísNacimiento: "Colombia",
    fechaNacimiento: "10-02-1955",
    fechaDefuncion: "1-12-2011",
    genero: "masculino",
    librosPublicados: ["a", "b"],
    nobel: false,
    anoNobel: "1980",
    premiosGanados: ["a", "b"],
    biografia: "a",
  },
];
