let listaLibros = [
  {
    id: "1",
    name: "El Diario de Ana Frank",
    author: "Ana Frank",
    img: "/ProjectGM_IMG/books/el_diario.jpg",
    price: 7000,
    stock: true,
    discount: false,
    gender: "Biografía",
    idiom: "Español",
  },
  {
    id: "2",
    name: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    img: "/ProjectGM_IMG/books/harry_potter.jpg",
    price: 6000,
    stock: true,
    discount: false,
    gender: "Ficción",
    idiom: "Español",
  },
  {
    id: "3",
    name: "The Hunger Games",
    author: "Suzanne Collins",
    img: "/ProjectGM_IMG/books/hunger_games.jpg",
    price: 6500,
    stock: true,
    discount: false,
    gender: "Ciencia ficción",
    idiom: "Español",
  },
  {
    id: "4",
    name: "The Lord Of The Rings",
    author: "J.R.R. Tolkien",
    img: "/ProjectGM_IMG/books/lord_of_the_rings.jpg",
    price: 8000,
    stock: true,
    discount: false,
    gender: "Ficción",
    idiom: "Español",
  },
  {
    id: "5",
    name: "Cien años de soledad",
    author: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/books/100annos.jpg",
    price: 4000,
    stock: true,
    discount: false,
    gender: "Novela",
    idiom: "Español",
  },
  {
    id: "6",
    name: "Cuentos de mi tía Panchita",
    author: "Carmen Lyra",
    img: "/ProjectGM_IMG/books/panchita.jpg",
    price: 4000,
    stock: true,
    discount: false,
    gender: "Cuentos",
    idiom: "Español",
  },
  {
    id: "7",
    name: "Enigma",
    author: "Robert Harris",
    img: "/ProjectGM_IMG/books/enigma-book7.jpg",
    price: 4500,
    stock: true,
    discount: false,
    gender: "Novela bélica",
    idiom: "Español",
  },
  {
    id: "8",
    name: "Gantz",
    author: "Hiroya Oku",
    img: "/ProjectGM_IMG/books/gantz-book8.jpg",
    price: 8000,
    stock: true,
    discount: false,
    gender: "Ciencia ficción",
    idiom: "Español",
  },
  {
    id: "9",
    name: "Viaje al reino de los deseos",
    author: "Rafael Ángel Herra",
    img: "/ProjectGM_IMG/books/viajealreino-book9.jpg",
    price: 3700,
    stock: true,
    discount: false,
    gender: "Fantasía",
    idiom: "Español",
  },
  {
    id: "10",
    name: "La metamorfosis",
    author: "Franz Kafka",
    img: "/ProjectGM_IMG/books/lameta-book10.jpg",
    price: 2850,
    stock: true,
    discount: false,
    gender: "Novela corta",
    idiom: "Español",
  },
];
