let listaLibros = [
  {
    id: "1",
    name: "El Diario de Ana Frank",
    author: "Ana Frank",
    img: "/ProjectGM_IMG/books/el_diario.jpg",
    price: 7000,
    stock: true,
    active: true,
    gender: "Biografía",
    idiom: "Español",
    authorId: "11",
    genderId: "6",
    discountId: "",
  },
  {
    id: "2",
    name: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    img: "/ProjectGM_IMG/books/harry_potter.jpg",
    price: 6000,
    stock: true,
    active: true,
    gender: "Ficción",
    idiom: "Español",
    authorId: "12",
    genderId: "7",
    discountId: "",
  },
  {
    id: "3",
    name: "The Hunger Games",
    author: "Suzanne Collins",
    img: "/ProjectGM_IMG/books/hunger_games.jpg",
    price: 6500,
    stock: true,
    active: true,
    gender: "Ciencia ficción",
    idiom: "Español",
    authorId: "13",
    genderId: "8",
    discountId: "",
  },
  {
    id: "4",
    name: "The Lord Of The Rings",
    author: "J.R.R. Tolkien",
    img: "/ProjectGM_IMG/books/lord_of_the_rings.jpg",
    price: 8000,
    stock: true,
    active: true,
    gender: "Ficción",
    idiom: "Español",
    authorId: "14",
    genderId: "7",
    discountId: "",
  },
  {
    id: "5",
    name: "Cien años de soledad",
    author: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/books/100anos.jpg",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "1",
    genderId: "5",
    discountId: "",
  },
  {
    id: "6",
    name: "Cuentos de mi tía Panchita",
    author: "Carmen Lyra",
    img: "/ProjectGM_IMG/books/panchita.jpg",
    price: 4000,
    stock: true,
    active: true,
    gender: "Cuento",
    idiom: "Español",
    authorId: "15",
    genderId: "9",
    discountId: "",
  },
  {
    id: "7",
    name: "Enigma",
    author: "Robert Harris",
    img: "/ProjectGM_IMG/books/enigma-book7.jpg",
    price: 4500,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "16",
    genderId: "5",
    discountId: "",
  },
  {
    id: "8",
    name: "Gantz",
    author: "Hiroya Oku",
    img: "/ProjectGM_IMG/books/gantz-book8.jpg",
    price: 8000,
    stock: true,
    active: true,
    gender: "Ciencia ficción",
    idiom: "Español",
    authorId: "17",
    genderId: "8",
    discountId: "",
  },
  {
    id: "9",
    name: "Viaje al reino de los deseos",
    author: "Rafael Ángel Herra",
    img: "/ProjectGM_IMG/books/viajealreino-book9.jpg",
    price: 3700,
    stock: true,
    active: true,
    gender: "Fantasía",
    idiom: "Español",
    authorId: "18",
    genderId: "10",
    discountId: "",
  },
  {
    id: "10",
    name: "La metamorfosis",
    author: "Franz Kafka",
    img: "/ProjectGM_IMG/books/lameta-book10.jpg",
    price: 2850,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "19",
    genderId: "5",
    discountId: "",
  },
  {
    id: "11",
    name: "El amor en el tiempo del cólera",
    author: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "1",
    genderId: "5",
    discountId: "",
  },
  {
    id: "12",
    name: "El coronel no tiene quien le escriba",
    author: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "1",
    genderId: "5",
    discountId: "",
  },
  {
    id: "13",
    name: "Memorias de mis putas tristes",
    author: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "1",
    genderId: "5",
    discountId: "",
  },
  {
    id: "14",
    name: "Canto General",
    author: "Pablo Neruda",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "2",
    genderId: "5",
    discountId: "",
  },
  {
    id: "15",
    name: "Veinte poemas de amor y una canción desesperada",
    author: "Pablo Neruda",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "2",
    genderId: "5",
    discountId: "",
  },
  {
    id: "16",
    name: "Cien sonetos de amor",
    author: "Pablo Neruda",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "2",
    genderId: "5",
    discountId: "",
  },
  {
    id: "17",
    name: "La ciudad y los perros",
    author: "Mario Vargas Llosa",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "3",
    genderId: "5",
    discountId: "",
  },
  {
    id: "18",
    name: "La tía Julia y el escribidor",
    author: "Mario Vargas Llosa",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "3",
    genderId: "5",
    discountId: "",
  },
  {
    id: "19",
    name: "La fiesta del Chivo",
    author: "Mario Vargas Llosa",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "3",
    genderId: "5",
    discountId: "",
  },
  {
    id: "20",
    name: "Travesuras de la niña mala",
    author: "Mario Vargas Llosa",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "3",
    genderId: "5",
    discountId: "",
  },
  {
    id: "21",
    name: "La casa de los espíritus",
    author: "Isabel Allende",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "4",
    genderId: "5",
    discountId: "",
  },
  {
    id: "22",
    name: "De amor y de sombra",
    author: "Isabel Allende",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "4",
    genderId: "5",
    discountId: "",
  },
  {
    id: "23",
    name: "El bosque de los pigmeos",
    author: "Isabel Allende",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "4",
    genderId: "5",
    discountId: "",
  },
  {
    id: "24",
    name: "El cuaderno de Maya",
    author: "Isabel Allende",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "4",
    genderId: "5",
    discountId: "",
  },
  {
    id: "25",
    name: "Ismaelillo",
    author: "José Martí",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "5",
    genderId: "5",
    discountId: "",
  },
  {
    id: "26",
    name: "Versos sencillos",
    author: "José Martí",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "5",
    genderId: "5",
    discountId: "",
  },
  {
    id: "27",
    name: "Inquisiciones",
    author: "Jorge Luis Borges",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "6",
    genderId: "5",
    discountId: "",
  },
  {
    id: "28",
    name: "El tamaño de mi esperanza",
    author: "Jorge Luis Borges",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "6",
    genderId: "5",
    discountId: "",
  },
  {
    id: "29",
    name: "Historia de la eternidad",
    author: "Jorge Luis Borges",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "6",
    genderId: "5",
    discountId: "",
  },
  {
    id: "30",
    name: "Antología personal",
    author: "Jorge Luis Borges",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "6",
    genderId: "5",
    discountId: "",
  },
  {
    id: "31",
    name: "Rayuela",
    author: "Julio Cortázar",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "7",
    genderId: "5",
    discountId: "",
  },
  {
    id: "32",
    name: "Antología",
    author: "Julio Cortázar",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "7",
    genderId: "5",
    discountId: "",
  },
  {
    id: "33",
    name: "Argentina, años de alambradas culturales",
    author: "Julio Cortázar",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "7",
    genderId: "5",
    discountId: "",
  },
  {
    id: "34",
    name: "Salvo el crepúsculo",
    author: "Julio Cortázar",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "7",
    genderId: "5",
    discountId: "",
  },
  {
    id: "35",
    name: "El pozo",
    author: "Juan Carlos Onetti",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "8",
    genderId: "5",
    discountId: "",
  },
  {
    id: "36",
    name: "Tierra de nadie",
    author: "Juan Carlos Onetti",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "8",
    genderId: "5",
    discountId: "",
  },
  {
    id: "37",
    name: "Para esta noche",
    author: "Juan Carlos Onetti",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "8",
    genderId: "5",
    discountId: "",
  },
  {
    id: "38",
    name: "La vida breve",
    author: "Juan Carlos Onetti",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "8",
    genderId: "5",
    discountId: "",
  },
  {
    id: "39",
    name: "Mar Muerto",
    author: "Jorge Amado",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "9",
    genderId: "5",
    discountId: "",
  },
  {
    id: "40",
    name: "Capitanes de la arena",
    author: "Jorge Amado",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "9",
    genderId: "5",
    discountId: "",
  },
  {
    id: "41",
    name: "Gabriela, clavo y canela",
    author: "Jorge Amado",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "9",
    genderId: "5",
    discountId: "",
  },
  {
    id: "42",
    name: "Los pastores de la noche",
    author: "Jorge Amado",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "9",
    genderId: "5",
    discountId: "",
  },
  {
    id: "43",
    name: "El señor presidente",
    author: "Miguel Asturias",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "10",
    genderId: "5",
    discountId: "",
  },
  {
    id: "44",
    name: "Hombres de maíz",
    author: "Miguel Asturias",
    img: "/ProjectGM_IMG/books/",
    price: 4000,
    stock: true,
    active: true,
    gender: "Novela",
    idiom: "Español",
    authorId: "10",
    genderId: "5",
    discountId: "",
  },
];
