let listaUsuarios = [
  {
    tipo: 1,
    correo: "victor@bazar.com",
    nombre: "Víctor Vargas Jiménez",
    nacimiento: "1994-02-25",
    contrasena: "admin123",
    position: "Administrador General",
    schedule: "Lunes a viernes de 7:00 - 16:00",
  },
  {
    tipo: 2,
    nombre: "Jazmín",
    primerApellido: "Alfaro",
    segundoApellido: "Castañeda",
    genero: "Femenino",
    tipoId: "Cédula de identidad",
    id: "12345612",
    correo: "jazmin@gmail.com",
    contrasena: "Cenfotec123",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    nacimiento: "1992-01-06",
  },
  {
    tipo: 2,
    correo: "jose@gmail.com",
    nombre: "José Cabrera",
    nacimiento: "1988-11-16",
    contrasena: "Cenfotec123",
  },
  {
    tipo: 2,
    correo: "ivan@gmail.com",
    nombre: "Iván Rojas",
    nacimiento: "1990-12-18",
    contrasena: "Cenfotec123",
  },
];
