let listaUsuarios = [
  {
    "id": 1,
    "tipoUsuario": 1,
    "tipoId": "Cédula de identidad",
    "identificacion": "123456789",
    "correo": "catalina@bazar.com",
    "contrasena": "Admin123",
    "nombre": "Catalina",
    "primerApellido": "Pérez",
    "segundoApellido": "Alvarado",
    "genero": "Femenino",
    "provincia": "Alajuela",
    "canton": "Grecia",
    "distrito": "Tacares",
    "direccion": "300 mts norte del mercado",
    "position": "Administrador General",
    "schedule": "Lunes a viernes de 7:00 - 16:00",
    "telefono": "86987412",
    "oficina": "Heredia",
  },
  {
    id: 2,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "12345612",
    correo: "fernando@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "Fernando",
    primerApellido: "Sancho",
    segundoApellido: "Barboza",
    genero: "Masculino",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generosFavoritos: ["Narrativo", "Cuentos"],
    autoresFavoritos: ["Gabriel García Márquez"],
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 3,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "452361612",
    correo: "luis@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "Luis",
    primerApellido: "Pérez",
    segundoApellido: "Hernández",
    genero: "Masculino",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generosFavoritos: "Narrativo",
    autoresFavoritos: "Gabriel García Márquez",
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
  {
    id: 4,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "65985454",
    correo: "maria@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "María",
    primerApellido: "Oviedo",
    segundoApellido: "Zúñiga",
    genero: "Femenino",
    provincia: "Alajuela",
    canton: "San Ramón",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generosFavoritos: "Narrativo",
    autoresFavoritos: "Gabriel García Márquez",
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 5,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "69874563",
    correo: "olga@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "Olga",
    primerApellido: "Vargas",
    segundoApellido: "Mora",
    genero: "Femenino",
    provincia: "Heredia",
    canton: "San Rafael",
    distrito: "Santiago",
    direccion: "100mts este del parque central",
    generosFavoritos: "Narrativo",
    autoresFavoritos: "Gabriel García Márquez",
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
  {
    id: 6,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "3451612",
    correo: "eduardo@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "Eduardo",
    primerApellido: "Carranza",
    segundoApellido: "López",
    genero: "Masculino",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generosFavoritos: "Narrativo",
    autoresFavoritos: "Gabriel García Márquez",
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 7,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "22031612",
    correo: "hernan@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "Hernán",
    primerApellido: "Ruiz",
    segundoApellido: "Chavarría",
    genero: "Masculino",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generosFavoritos: "Narrativo",
    autoresFavoritos: "Gabriel García Márquez",
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
  {
    id: 8,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "70185454",
    correo: "juana@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "Juana",
    primerApellido: "Charpentier",
    segundoApellido: "Hidalgo",
    genero: "Femenino",
    provincia: "Alajuela",
    canton: "San Ramón",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generosFavoritos: "Narrativo",
    autoresFavoritos: "Gabriel García Márquez",
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 9,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "3974563",
    correo: "danilo@gmail.com",
    contrasena: "Cenfotec123",
    nombre: "Danilo",
    primerApellido: "Jiménez",
    segundoApellido: "Calderón",
    genero: "Masculino",
    provincia: "Heredia",
    canton: "San Rafael",
    distrito: "Santiago",
    direccion: "100mts este del parque central",
    generosFavoritos: "Narrativo",
    autoresFavoritos: "Gabriel García Márquez",
    foto: "/ProjectGM_foto/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
];
