let listaUsuarios = [
  {
    id: 1,
    tipoUsuario: 1,
    tipoId: "Cédula de identidad",
    identificacion: "123456789",
    correo: "catalina@bazar.com",
    contrasena: "Admin123",
    nacimiento: "1994-02-25",
    nombre: "Catalina",
    primerApellido: "Pérez",
    segundoApellido: "Alvarado",
    genero: "Femenino",
    pais: "Costa Rica",
    provincia: "Alajuela",
    canton: "Grecia",
    distrito: "Tacares",
    direccion: "300 mts norte del mercado",
    position: "Administrador General",
    schedule: "Lunes a viernes de 7:00 - 16:00",
    telefono: "86987412",
    oficina: "Heredia",
  },
  {
    id: 2,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "12345612",
    correo: "fernando@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "Fernando",
    primerApellido: "Sancho",
    segundoApellido: "Barboza",
    genero: "Masculino",
    pais: "Costa Rica",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 3,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "452361612",
    correo: "luis@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "Luis",
    primerApellido: "Pérez",
    segundoApellido: "Hernández",
    genero: "Masculino",
    pais: "Costa Rica",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
  {
    id: 4,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "65985454",
    correo: "maria@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "María",
    primerApellido: "Oviedo",
    segundoApellido: "Zúñiga",
    genero: "Femenino",
    pais: "Costa Rica",
    provincia: "Alajuela",
    canton: "San Ramón",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 5,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "69874563",
    correo: "olga@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "Olga",
    primerApellido: "Vargas",
    segundoApellido: "Mora",
    genero: "Femenino",
    pais: "Costa Rica",
    provincia: "Heredia",
    canton: "San Rafael",
    distrito: "Santiago",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
  {
    id: 6,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "3451612",
    correo: "eduardo@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "Eduardo",
    primerApellido: "Carranza",
    segundoApellido: "López",
    genero: "Masculino",
    pais: "Costa Rica",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 7,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "22031612",
    correo: "hernan@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "Hernán",
    primerApellido: "Ruiz",
    segundoApellido: "Chavarría",
    genero: "Masculino",
    pais: "Costa Rica",
    provincia: "San José",
    canton: "Montes de Oca",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
  {
    id: 8,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "70185454",
    correo: "juana@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "Juana",
    primerApellido: "Charpentier",
    segundoApellido: "Hidalgo",
    genero: "Femenino",
    pais: "Costa Rica",
    provincia: "Alajuela",
    canton: "San Ramón",
    distrito: "San Pedro",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: true,
  },
  {
    id: 9,
    tipoUsuario: 2,
    tipoId: "Cédula de identidad",
    identificacion: "3974563",
    correo: "danilo@gmail.com",
    contrasena: "Cenfotec123",
    nacimiento: "1992-01-06",
    nombre: "Danilo",
    primerApellido: "Jiménez",
    segundoApellido: "Calderón",
    genero: "Masculino",
    pais: "Costa Rica",
    provincia: "Heredia",
    canton: "San Rafael",
    distrito: "Santiago",
    direccion: "100mts este del parque central",
    generoFavorito: "Narrativo",
    autorFavorito: "Gabriel García Márquez",
    img: "/ProjectGM_IMG/clientes/fernando_sancho_barboza.jpg",
    libroFan: false,
  },
];
